package menuXmlmapper.model;

import java.util.Date;

public class SystemDomainMenuText {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column system_domain_menu_text.menu_text_id
     *
     * @mbg.generated Thu Dec 18 16:02:35 KST 2025
     */
    private String menuTextId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column system_domain_menu_text.menu_item_id
     *
     * @mbg.generated Thu Dec 18 16:02:35 KST 2025
     */
    private String menuItemId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column system_domain_menu_text.text
     *
     * @mbg.generated Thu Dec 18 16:02:35 KST 2025
     */
    private String text;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column system_domain_menu_text.language_code
     *
     * @mbg.generated Thu Dec 18 16:02:35 KST 2025
     */
    private String languageCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column system_domain_menu_text.creator
     *
     * @mbg.generated Thu Dec 18 16:02:35 KST 2025
     */
    private String creator;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column system_domain_menu_text.created
     *
     * @mbg.generated Thu Dec 18 16:02:35 KST 2025
     */
    private Date created;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column system_domain_menu_text.modifier
     *
     * @mbg.generated Thu Dec 18 16:02:35 KST 2025
     */
    private String modifier;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column system_domain_menu_text.modified
     *
     * @mbg.generated Thu Dec 18 16:02:35 KST 2025
     */
    private Date modified;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column system_domain_menu_text.menu_text_id
     *
     * @return the value of system_domain_menu_text.menu_text_id
     *
     * @mbg.generated Thu Dec 18 16:02:35 KST 2025
     */
    public String getMenuTextId() {
        return menuTextId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column system_domain_menu_text.menu_text_id
     *
     * @param menuTextId the value for system_domain_menu_text.menu_text_id
     *
     * @mbg.generated Thu Dec 18 16:02:35 KST 2025
     */
    public void setMenuTextId(String menuTextId) {
        this.menuTextId = menuTextId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column system_domain_menu_text.menu_item_id
     *
     * @return the value of system_domain_menu_text.menu_item_id
     *
     * @mbg.generated Thu Dec 18 16:02:35 KST 2025
     */
    public String getMenuItemId() {
        return menuItemId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column system_domain_menu_text.menu_item_id
     *
     * @param menuItemId the value for system_domain_menu_text.menu_item_id
     *
     * @mbg.generated Thu Dec 18 16:02:35 KST 2025
     */
    public void setMenuItemId(String menuItemId) {
        this.menuItemId = menuItemId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column system_domain_menu_text.text
     *
     * @return the value of system_domain_menu_text.text
     *
     * @mbg.generated Thu Dec 18 16:02:35 KST 2025
     */
    public String getText() {
        return text;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column system_domain_menu_text.text
     *
     * @param text the value for system_domain_menu_text.text
     *
     * @mbg.generated Thu Dec 18 16:02:35 KST 2025
     */
    public void setText(String text) {
        this.text = text;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column system_domain_menu_text.language_code
     *
     * @return the value of system_domain_menu_text.language_code
     *
     * @mbg.generated Thu Dec 18 16:02:35 KST 2025
     */
    public String getLanguageCode() {
        return languageCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column system_domain_menu_text.language_code
     *
     * @param languageCode the value for system_domain_menu_text.language_code
     *
     * @mbg.generated Thu Dec 18 16:02:35 KST 2025
     */
    public void setLanguageCode(String languageCode) {
        this.languageCode = languageCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column system_domain_menu_text.creator
     *
     * @return the value of system_domain_menu_text.creator
     *
     * @mbg.generated Thu Dec 18 16:02:35 KST 2025
     */
    public String getCreator() {
        return creator;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column system_domain_menu_text.creator
     *
     * @param creator the value for system_domain_menu_text.creator
     *
     * @mbg.generated Thu Dec 18 16:02:35 KST 2025
     */
    public void setCreator(String creator) {
        this.creator = creator;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column system_domain_menu_text.created
     *
     * @return the value of system_domain_menu_text.created
     *
     * @mbg.generated Thu Dec 18 16:02:35 KST 2025
     */
    public Date getCreated() {
        return created;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column system_domain_menu_text.created
     *
     * @param created the value for system_domain_menu_text.created
     *
     * @mbg.generated Thu Dec 18 16:02:35 KST 2025
     */
    public void setCreated(Date created) {
        this.created = created;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column system_domain_menu_text.modifier
     *
     * @return the value of system_domain_menu_text.modifier
     *
     * @mbg.generated Thu Dec 18 16:02:35 KST 2025
     */
    public String getModifier() {
        return modifier;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column system_domain_menu_text.modifier
     *
     * @param modifier the value for system_domain_menu_text.modifier
     *
     * @mbg.generated Thu Dec 18 16:02:35 KST 2025
     */
    public void setModifier(String modifier) {
        this.modifier = modifier;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column system_domain_menu_text.modified
     *
     * @return the value of system_domain_menu_text.modified
     *
     * @mbg.generated Thu Dec 18 16:02:35 KST 2025
     */
    public Date getModified() {
        return modified;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column system_domain_menu_text.modified
     *
     * @param modified the value for system_domain_menu_text.modified
     *
     * @mbg.generated Thu Dec 18 16:02:35 KST 2025
     */
    public void setModified(Date modified) {
        this.modified = modified;
    }
}