package menuXmlmapper.model;

import java.util.Date;

public class SystemDomainMenuItem {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column system_domain_menu_item.menu_item_id
     *
     * @mbg.generated Thu Dec 18 16:02:35 KST 2025
     */
    private String menuItemId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column system_domain_menu_item.menu_code
     *
     * @mbg.generated Thu Dec 18 16:02:35 KST 2025
     */
    private String menuCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column system_domain_menu_item.parent_menu_item
     *
     * @mbg.generated Thu Dec 18 16:02:35 KST 2025
     */
    private String parentMenuItem;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column system_domain_menu_item.menu_text
     *
     * @mbg.generated Thu Dec 18 16:02:35 KST 2025
     */
    private String menuText;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column system_domain_menu_item.target_url
     *
     * @mbg.generated Thu Dec 18 16:02:35 KST 2025
     */
    private String targetUrl;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column system_domain_menu_item.sort_order
     *
     * @mbg.generated Thu Dec 18 16:02:35 KST 2025
     */
    private Short sortOrder;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column system_domain_menu_item.is_active
     *
     * @mbg.generated Thu Dec 18 16:02:35 KST 2025
     */
    private Boolean isActive;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column system_domain_menu_item.icon_class
     *
     * @mbg.generated Thu Dec 18 16:02:35 KST 2025
     */
    private String iconClass;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column system_domain_menu_item.sensitivity_level
     *
     * @mbg.generated Thu Dec 18 16:02:35 KST 2025
     */
    private String sensitivityLevel;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column system_domain_menu_item.creator
     *
     * @mbg.generated Thu Dec 18 16:02:35 KST 2025
     */
    private String creator;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column system_domain_menu_item.created
     *
     * @mbg.generated Thu Dec 18 16:02:35 KST 2025
     */
    private Date created;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column system_domain_menu_item.modifier
     *
     * @mbg.generated Thu Dec 18 16:02:35 KST 2025
     */
    private String modifier;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column system_domain_menu_item.modified
     *
     * @mbg.generated Thu Dec 18 16:02:35 KST 2025
     */
    private Date modified;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column system_domain_menu_item.menu_item_id
     *
     * @return the value of system_domain_menu_item.menu_item_id
     *
     * @mbg.generated Thu Dec 18 16:02:35 KST 2025
     */
    public String getMenuItemId() {
        return menuItemId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column system_domain_menu_item.menu_item_id
     *
     * @param menuItemId the value for system_domain_menu_item.menu_item_id
     *
     * @mbg.generated Thu Dec 18 16:02:35 KST 2025
     */
    public void setMenuItemId(String menuItemId) {
        this.menuItemId = menuItemId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column system_domain_menu_item.menu_code
     *
     * @return the value of system_domain_menu_item.menu_code
     *
     * @mbg.generated Thu Dec 18 16:02:35 KST 2025
     */
    public String getMenuCode() {
        return menuCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column system_domain_menu_item.menu_code
     *
     * @param menuCode the value for system_domain_menu_item.menu_code
     *
     * @mbg.generated Thu Dec 18 16:02:35 KST 2025
     */
    public void setMenuCode(String menuCode) {
        this.menuCode = menuCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column system_domain_menu_item.parent_menu_item
     *
     * @return the value of system_domain_menu_item.parent_menu_item
     *
     * @mbg.generated Thu Dec 18 16:02:35 KST 2025
     */
    public String getParentMenuItem() {
        return parentMenuItem;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column system_domain_menu_item.parent_menu_item
     *
     * @param parentMenuItem the value for system_domain_menu_item.parent_menu_item
     *
     * @mbg.generated Thu Dec 18 16:02:35 KST 2025
     */
    public void setParentMenuItem(String parentMenuItem) {
        this.parentMenuItem = parentMenuItem;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column system_domain_menu_item.menu_text
     *
     * @return the value of system_domain_menu_item.menu_text
     *
     * @mbg.generated Thu Dec 18 16:02:35 KST 2025
     */
    public String getMenuText() {
        return menuText;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column system_domain_menu_item.menu_text
     *
     * @param menuText the value for system_domain_menu_item.menu_text
     *
     * @mbg.generated Thu Dec 18 16:02:35 KST 2025
     */
    public void setMenuText(String menuText) {
        this.menuText = menuText;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column system_domain_menu_item.target_url
     *
     * @return the value of system_domain_menu_item.target_url
     *
     * @mbg.generated Thu Dec 18 16:02:35 KST 2025
     */
    public String getTargetUrl() {
        return targetUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column system_domain_menu_item.target_url
     *
     * @param targetUrl the value for system_domain_menu_item.target_url
     *
     * @mbg.generated Thu Dec 18 16:02:35 KST 2025
     */
    public void setTargetUrl(String targetUrl) {
        this.targetUrl = targetUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column system_domain_menu_item.sort_order
     *
     * @return the value of system_domain_menu_item.sort_order
     *
     * @mbg.generated Thu Dec 18 16:02:35 KST 2025
     */
    public Short getSortOrder() {
        return sortOrder;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column system_domain_menu_item.sort_order
     *
     * @param sortOrder the value for system_domain_menu_item.sort_order
     *
     * @mbg.generated Thu Dec 18 16:02:35 KST 2025
     */
    public void setSortOrder(Short sortOrder) {
        this.sortOrder = sortOrder;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column system_domain_menu_item.is_active
     *
     * @return the value of system_domain_menu_item.is_active
     *
     * @mbg.generated Thu Dec 18 16:02:35 KST 2025
     */
    public Boolean getIsActive() {
        return isActive;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column system_domain_menu_item.is_active
     *
     * @param isActive the value for system_domain_menu_item.is_active
     *
     * @mbg.generated Thu Dec 18 16:02:35 KST 2025
     */
    public void setIsActive(Boolean isActive) {
        this.isActive = isActive;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column system_domain_menu_item.icon_class
     *
     * @return the value of system_domain_menu_item.icon_class
     *
     * @mbg.generated Thu Dec 18 16:02:35 KST 2025
     */
    public String getIconClass() {
        return iconClass;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column system_domain_menu_item.icon_class
     *
     * @param iconClass the value for system_domain_menu_item.icon_class
     *
     * @mbg.generated Thu Dec 18 16:02:35 KST 2025
     */
    public void setIconClass(String iconClass) {
        this.iconClass = iconClass;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column system_domain_menu_item.sensitivity_level
     *
     * @return the value of system_domain_menu_item.sensitivity_level
     *
     * @mbg.generated Thu Dec 18 16:02:35 KST 2025
     */
    public String getSensitivityLevel() {
        return sensitivityLevel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column system_domain_menu_item.sensitivity_level
     *
     * @param sensitivityLevel the value for system_domain_menu_item.sensitivity_level
     *
     * @mbg.generated Thu Dec 18 16:02:35 KST 2025
     */
    public void setSensitivityLevel(String sensitivityLevel) {
        this.sensitivityLevel = sensitivityLevel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column system_domain_menu_item.creator
     *
     * @return the value of system_domain_menu_item.creator
     *
     * @mbg.generated Thu Dec 18 16:02:35 KST 2025
     */
    public String getCreator() {
        return creator;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column system_domain_menu_item.creator
     *
     * @param creator the value for system_domain_menu_item.creator
     *
     * @mbg.generated Thu Dec 18 16:02:35 KST 2025
     */
    public void setCreator(String creator) {
        this.creator = creator;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column system_domain_menu_item.created
     *
     * @return the value of system_domain_menu_item.created
     *
     * @mbg.generated Thu Dec 18 16:02:35 KST 2025
     */
    public Date getCreated() {
        return created;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column system_domain_menu_item.created
     *
     * @param created the value for system_domain_menu_item.created
     *
     * @mbg.generated Thu Dec 18 16:02:35 KST 2025
     */
    public void setCreated(Date created) {
        this.created = created;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column system_domain_menu_item.modifier
     *
     * @return the value of system_domain_menu_item.modifier
     *
     * @mbg.generated Thu Dec 18 16:02:35 KST 2025
     */
    public String getModifier() {
        return modifier;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column system_domain_menu_item.modifier
     *
     * @param modifier the value for system_domain_menu_item.modifier
     *
     * @mbg.generated Thu Dec 18 16:02:35 KST 2025
     */
    public void setModifier(String modifier) {
        this.modifier = modifier;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column system_domain_menu_item.modified
     *
     * @return the value of system_domain_menu_item.modified
     *
     * @mbg.generated Thu Dec 18 16:02:35 KST 2025
     */
    public Date getModified() {
        return modified;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column system_domain_menu_item.modified
     *
     * @param modified the value for system_domain_menu_item.modified
     *
     * @mbg.generated Thu Dec 18 16:02:35 KST 2025
     */
    public void setModified(Date modified) {
        this.modified = modified;
    }
}