package menuXmlmapper.model;

import java.util.Date;

public class SystemDomainMenuAttributeTag {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column system_domain_menu_attribute_tag.menu_attribute_tag_id
     *
     * @mbg.generated Thu Dec 18 16:02:35 KST 2025
     */
    private String menuAttributeTagId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column system_domain_menu_attribute_tag.menu_item_id
     *
     * @mbg.generated Thu Dec 18 16:02:35 KST 2025
     */
    private String menuItemId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column system_domain_menu_attribute_tag.attribute
     *
     * @mbg.generated Thu Dec 18 16:02:35 KST 2025
     */
    private String attribute;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column system_domain_menu_attribute_tag.tag
     *
     * @mbg.generated Thu Dec 18 16:02:35 KST 2025
     */
    private String tag;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column system_domain_menu_attribute_tag.creator
     *
     * @mbg.generated Thu Dec 18 16:02:35 KST 2025
     */
    private String creator;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column system_domain_menu_attribute_tag.created
     *
     * @mbg.generated Thu Dec 18 16:02:35 KST 2025
     */
    private Date created;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column system_domain_menu_attribute_tag.modifier
     *
     * @mbg.generated Thu Dec 18 16:02:35 KST 2025
     */
    private String modifier;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column system_domain_menu_attribute_tag.modified
     *
     * @mbg.generated Thu Dec 18 16:02:35 KST 2025
     */
    private Date modified;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column system_domain_menu_attribute_tag.menu_attribute_tag_id
     *
     * @return the value of system_domain_menu_attribute_tag.menu_attribute_tag_id
     *
     * @mbg.generated Thu Dec 18 16:02:35 KST 2025
     */
    public String getMenuAttributeTagId() {
        return menuAttributeTagId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column system_domain_menu_attribute_tag.menu_attribute_tag_id
     *
     * @param menuAttributeTagId the value for system_domain_menu_attribute_tag.menu_attribute_tag_id
     *
     * @mbg.generated Thu Dec 18 16:02:35 KST 2025
     */
    public void setMenuAttributeTagId(String menuAttributeTagId) {
        this.menuAttributeTagId = menuAttributeTagId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column system_domain_menu_attribute_tag.menu_item_id
     *
     * @return the value of system_domain_menu_attribute_tag.menu_item_id
     *
     * @mbg.generated Thu Dec 18 16:02:35 KST 2025
     */
    public String getMenuItemId() {
        return menuItemId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column system_domain_menu_attribute_tag.menu_item_id
     *
     * @param menuItemId the value for system_domain_menu_attribute_tag.menu_item_id
     *
     * @mbg.generated Thu Dec 18 16:02:35 KST 2025
     */
    public void setMenuItemId(String menuItemId) {
        this.menuItemId = menuItemId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column system_domain_menu_attribute_tag.attribute
     *
     * @return the value of system_domain_menu_attribute_tag.attribute
     *
     * @mbg.generated Thu Dec 18 16:02:35 KST 2025
     */
    public String getAttribute() {
        return attribute;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column system_domain_menu_attribute_tag.attribute
     *
     * @param attribute the value for system_domain_menu_attribute_tag.attribute
     *
     * @mbg.generated Thu Dec 18 16:02:35 KST 2025
     */
    public void setAttribute(String attribute) {
        this.attribute = attribute;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column system_domain_menu_attribute_tag.tag
     *
     * @return the value of system_domain_menu_attribute_tag.tag
     *
     * @mbg.generated Thu Dec 18 16:02:35 KST 2025
     */
    public String getTag() {
        return tag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column system_domain_menu_attribute_tag.tag
     *
     * @param tag the value for system_domain_menu_attribute_tag.tag
     *
     * @mbg.generated Thu Dec 18 16:02:35 KST 2025
     */
    public void setTag(String tag) {
        this.tag = tag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column system_domain_menu_attribute_tag.creator
     *
     * @return the value of system_domain_menu_attribute_tag.creator
     *
     * @mbg.generated Thu Dec 18 16:02:35 KST 2025
     */
    public String getCreator() {
        return creator;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column system_domain_menu_attribute_tag.creator
     *
     * @param creator the value for system_domain_menu_attribute_tag.creator
     *
     * @mbg.generated Thu Dec 18 16:02:35 KST 2025
     */
    public void setCreator(String creator) {
        this.creator = creator;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column system_domain_menu_attribute_tag.created
     *
     * @return the value of system_domain_menu_attribute_tag.created
     *
     * @mbg.generated Thu Dec 18 16:02:35 KST 2025
     */
    public Date getCreated() {
        return created;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column system_domain_menu_attribute_tag.created
     *
     * @param created the value for system_domain_menu_attribute_tag.created
     *
     * @mbg.generated Thu Dec 18 16:02:35 KST 2025
     */
    public void setCreated(Date created) {
        this.created = created;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column system_domain_menu_attribute_tag.modifier
     *
     * @return the value of system_domain_menu_attribute_tag.modifier
     *
     * @mbg.generated Thu Dec 18 16:02:35 KST 2025
     */
    public String getModifier() {
        return modifier;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column system_domain_menu_attribute_tag.modifier
     *
     * @param modifier the value for system_domain_menu_attribute_tag.modifier
     *
     * @mbg.generated Thu Dec 18 16:02:35 KST 2025
     */
    public void setModifier(String modifier) {
        this.modifier = modifier;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column system_domain_menu_attribute_tag.modified
     *
     * @return the value of system_domain_menu_attribute_tag.modified
     *
     * @mbg.generated Thu Dec 18 16:02:35 KST 2025
     */
    public Date getModified() {
        return modified;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column system_domain_menu_attribute_tag.modified
     *
     * @param modified the value for system_domain_menu_attribute_tag.modified
     *
     * @mbg.generated Thu Dec 18 16:02:35 KST 2025
     */
    public void setModified(Date modified) {
        this.modified = modified;
    }
}