package menuXmlmapper.dao;

import java.util.List;
import menuXmlmapper.model.SystemDomainMenuText;
import menuXmlmapper.model.SystemDomainMenuTextExample;
import org.apache.ibatis.annotations.Delete;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.ResultMap;
import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.annotations.Update;

public interface SystemDomainMenuTextMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table system_domain_menu_text
     *
     * @mbg.generated Thu Dec 18 16:02:35 KST 2025
     */
    long countByExample(SystemDomainMenuTextExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table system_domain_menu_text
     *
     * @mbg.generated Thu Dec 18 16:02:35 KST 2025
     */
    int deleteByExample(SystemDomainMenuTextExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table system_domain_menu_text
     *
     * @mbg.generated Thu Dec 18 16:02:35 KST 2025
     */
    @Delete({
        "delete from system_domain_menu_text",
        "where menu_text_id = #{menuTextId,jdbcType=VARCHAR}"
    })
    int deleteByPrimaryKey(String menuTextId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table system_domain_menu_text
     *
     * @mbg.generated Thu Dec 18 16:02:35 KST 2025
     */
    @Insert({
        "insert into system_domain_menu_text (menu_text_id, menu_item_id, ",
        "text, language_code, ",
        "creator, created, ",
        "modifier, modified)",
        "values (#{menuTextId,jdbcType=VARCHAR}, #{menuItemId,jdbcType=VARCHAR}, ",
        "#{text,jdbcType=VARCHAR}, #{languageCode,jdbcType=CHAR}, ",
        "#{creator,jdbcType=VARCHAR}, #{created,jdbcType=TIMESTAMP}, ",
        "#{modifier,jdbcType=VARCHAR}, #{modified,jdbcType=TIMESTAMP})"
    })
    int insert(SystemDomainMenuText row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table system_domain_menu_text
     *
     * @mbg.generated Thu Dec 18 16:02:35 KST 2025
     */
    int insertSelective(SystemDomainMenuText row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table system_domain_menu_text
     *
     * @mbg.generated Thu Dec 18 16:02:35 KST 2025
     */
    List<SystemDomainMenuText> selectByExample(SystemDomainMenuTextExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table system_domain_menu_text
     *
     * @mbg.generated Thu Dec 18 16:02:35 KST 2025
     */
    @Select({
        "select",
        "menu_text_id, menu_item_id, text, language_code, creator, created, modifier, ",
        "modified",
        "from system_domain_menu_text",
        "where menu_text_id = #{menuTextId,jdbcType=VARCHAR}"
    })
    @ResultMap("menuXmlmapper.dao.SystemDomainMenuTextMapper.BaseResultMap")
    SystemDomainMenuText selectByPrimaryKey(String menuTextId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table system_domain_menu_text
     *
     * @mbg.generated Thu Dec 18 16:02:35 KST 2025
     */
    int updateByExampleSelective(@Param("row") SystemDomainMenuText row, @Param("example") SystemDomainMenuTextExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table system_domain_menu_text
     *
     * @mbg.generated Thu Dec 18 16:02:35 KST 2025
     */
    int updateByExample(@Param("row") SystemDomainMenuText row, @Param("example") SystemDomainMenuTextExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table system_domain_menu_text
     *
     * @mbg.generated Thu Dec 18 16:02:35 KST 2025
     */
    int updateByPrimaryKeySelective(SystemDomainMenuText row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table system_domain_menu_text
     *
     * @mbg.generated Thu Dec 18 16:02:35 KST 2025
     */
    @Update({
        "update system_domain_menu_text",
        "set menu_item_id = #{menuItemId,jdbcType=VARCHAR},",
          "text = #{text,jdbcType=VARCHAR},",
          "language_code = #{languageCode,jdbcType=CHAR},",
          "creator = #{creator,jdbcType=VARCHAR},",
          "created = #{created,jdbcType=TIMESTAMP},",
          "modifier = #{modifier,jdbcType=VARCHAR},",
          "modified = #{modified,jdbcType=TIMESTAMP}",
        "where menu_text_id = #{menuTextId,jdbcType=VARCHAR}"
    })
    int updateByPrimaryKey(SystemDomainMenuText row);
}