package menuXmlmapper.dao;

import java.util.List;
import menuXmlmapper.model.SystemDomainMenuAttributeTag;
import menuXmlmapper.model.SystemDomainMenuAttributeTagExample;
import org.apache.ibatis.annotations.Delete;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.ResultMap;
import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.annotations.Update;

public interface SystemDomainMenuAttributeTagMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table system_domain_menu_attribute_tag
     *
     * @mbg.generated Thu Dec 18 16:02:35 KST 2025
     */
    long countByExample(SystemDomainMenuAttributeTagExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table system_domain_menu_attribute_tag
     *
     * @mbg.generated Thu Dec 18 16:02:35 KST 2025
     */
    int deleteByExample(SystemDomainMenuAttributeTagExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table system_domain_menu_attribute_tag
     *
     * @mbg.generated Thu Dec 18 16:02:35 KST 2025
     */
    @Delete({
        "delete from system_domain_menu_attribute_tag",
        "where menu_attribute_tag_id = #{menuAttributeTagId,jdbcType=VARCHAR}"
    })
    int deleteByPrimaryKey(String menuAttributeTagId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table system_domain_menu_attribute_tag
     *
     * @mbg.generated Thu Dec 18 16:02:35 KST 2025
     */
    @Insert({
        "insert into system_domain_menu_attribute_tag (menu_attribute_tag_id, menu_item_id, ",
        "attribute, tag, ",
        "creator, created, ",
        "modifier, modified)",
        "values (#{menuAttributeTagId,jdbcType=VARCHAR}, #{menuItemId,jdbcType=VARCHAR}, ",
        "#{attribute,jdbcType=VARCHAR}, #{tag,jdbcType=VARCHAR}, ",
        "#{creator,jdbcType=VARCHAR}, #{created,jdbcType=TIMESTAMP}, ",
        "#{modifier,jdbcType=VARCHAR}, #{modified,jdbcType=TIMESTAMP})"
    })
    int insert(SystemDomainMenuAttributeTag row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table system_domain_menu_attribute_tag
     *
     * @mbg.generated Thu Dec 18 16:02:35 KST 2025
     */
    int insertSelective(SystemDomainMenuAttributeTag row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table system_domain_menu_attribute_tag
     *
     * @mbg.generated Thu Dec 18 16:02:35 KST 2025
     */
    List<SystemDomainMenuAttributeTag> selectByExample(SystemDomainMenuAttributeTagExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table system_domain_menu_attribute_tag
     *
     * @mbg.generated Thu Dec 18 16:02:35 KST 2025
     */
    @Select({
        "select",
        "menu_attribute_tag_id, menu_item_id, attribute, tag, creator, created, modifier, ",
        "modified",
        "from system_domain_menu_attribute_tag",
        "where menu_attribute_tag_id = #{menuAttributeTagId,jdbcType=VARCHAR}"
    })
    @ResultMap("menuXmlmapper.dao.SystemDomainMenuAttributeTagMapper.BaseResultMap")
    SystemDomainMenuAttributeTag selectByPrimaryKey(String menuAttributeTagId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table system_domain_menu_attribute_tag
     *
     * @mbg.generated Thu Dec 18 16:02:35 KST 2025
     */
    int updateByExampleSelective(@Param("row") SystemDomainMenuAttributeTag row, @Param("example") SystemDomainMenuAttributeTagExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table system_domain_menu_attribute_tag
     *
     * @mbg.generated Thu Dec 18 16:02:35 KST 2025
     */
    int updateByExample(@Param("row") SystemDomainMenuAttributeTag row, @Param("example") SystemDomainMenuAttributeTagExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table system_domain_menu_attribute_tag
     *
     * @mbg.generated Thu Dec 18 16:02:35 KST 2025
     */
    int updateByPrimaryKeySelective(SystemDomainMenuAttributeTag row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table system_domain_menu_attribute_tag
     *
     * @mbg.generated Thu Dec 18 16:02:35 KST 2025
     */
    @Update({
        "update system_domain_menu_attribute_tag",
        "set menu_item_id = #{menuItemId,jdbcType=VARCHAR},",
          "attribute = #{attribute,jdbcType=VARCHAR},",
          "tag = #{tag,jdbcType=VARCHAR},",
          "creator = #{creator,jdbcType=VARCHAR},",
          "created = #{created,jdbcType=TIMESTAMP},",
          "modifier = #{modifier,jdbcType=VARCHAR},",
          "modified = #{modified,jdbcType=TIMESTAMP}",
        "where menu_attribute_tag_id = #{menuAttributeTagId,jdbcType=VARCHAR}"
    })
    int updateByPrimaryKey(SystemDomainMenuAttributeTag row);
}