package menuXmlmapper.dao;

import java.util.List;
import menuXmlmapper.model.SystemDomainMenuItem;
import menuXmlmapper.model.SystemDomainMenuItemExample;
import org.apache.ibatis.annotations.Delete;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.ResultMap;
import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.annotations.Update;

public interface SystemDomainMenuItemMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table system_domain_menu_item
     *
     * @mbg.generated Thu Dec 18 16:02:35 KST 2025
     */
    long countByExample(SystemDomainMenuItemExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table system_domain_menu_item
     *
     * @mbg.generated Thu Dec 18 16:02:35 KST 2025
     */
    int deleteByExample(SystemDomainMenuItemExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table system_domain_menu_item
     *
     * @mbg.generated Thu Dec 18 16:02:35 KST 2025
     */
    @Delete({
        "delete from system_domain_menu_item",
        "where menu_item_id = #{menuItemId,jdbcType=VARCHAR}"
    })
    int deleteByPrimaryKey(String menuItemId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table system_domain_menu_item
     *
     * @mbg.generated Thu Dec 18 16:02:35 KST 2025
     */
    @Insert({
        "insert into system_domain_menu_item (menu_item_id, menu_code, ",
        "parent_menu_item, menu_text, ",
        "target_url, sort_order, ",
        "is_active, icon_class, ",
        "sensitivity_level, creator, ",
        "created, modifier, ",
        "modified)",
        "values (#{menuItemId,jdbcType=VARCHAR}, #{menuCode,jdbcType=VARCHAR}, ",
        "#{parentMenuItem,jdbcType=VARCHAR}, #{menuText,jdbcType=VARCHAR}, ",
        "#{targetUrl,jdbcType=VARCHAR}, #{sortOrder,jdbcType=SMALLINT}, ",
        "#{isActive,jdbcType=BIT}, #{iconClass,jdbcType=VARCHAR}, ",
        "#{sensitivityLevel,jdbcType=VARCHAR}, #{creator,jdbcType=VARCHAR}, ",
        "#{created,jdbcType=TIMESTAMP}, #{modifier,jdbcType=VARCHAR}, ",
        "#{modified,jdbcType=TIMESTAMP})"
    })
    int insert(SystemDomainMenuItem row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table system_domain_menu_item
     *
     * @mbg.generated Thu Dec 18 16:02:35 KST 2025
     */
    int insertSelective(SystemDomainMenuItem row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table system_domain_menu_item
     *
     * @mbg.generated Thu Dec 18 16:02:35 KST 2025
     */
    List<SystemDomainMenuItem> selectByExample(SystemDomainMenuItemExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table system_domain_menu_item
     *
     * @mbg.generated Thu Dec 18 16:02:35 KST 2025
     */
    @Select({
        "select",
        "menu_item_id, menu_code, parent_menu_item, menu_text, target_url, sort_order, ",
        "is_active, icon_class, sensitivity_level, creator, created, modifier, modified",
        "from system_domain_menu_item",
        "where menu_item_id = #{menuItemId,jdbcType=VARCHAR}"
    })
    @ResultMap("menuXmlmapper.dao.SystemDomainMenuItemMapper.BaseResultMap")
    SystemDomainMenuItem selectByPrimaryKey(String menuItemId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table system_domain_menu_item
     *
     * @mbg.generated Thu Dec 18 16:02:35 KST 2025
     */
    int updateByExampleSelective(@Param("row") SystemDomainMenuItem row, @Param("example") SystemDomainMenuItemExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table system_domain_menu_item
     *
     * @mbg.generated Thu Dec 18 16:02:35 KST 2025
     */
    int updateByExample(@Param("row") SystemDomainMenuItem row, @Param("example") SystemDomainMenuItemExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table system_domain_menu_item
     *
     * @mbg.generated Thu Dec 18 16:02:35 KST 2025
     */
    int updateByPrimaryKeySelective(SystemDomainMenuItem row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table system_domain_menu_item
     *
     * @mbg.generated Thu Dec 18 16:02:35 KST 2025
     */
    @Update({
        "update system_domain_menu_item",
        "set menu_code = #{menuCode,jdbcType=VARCHAR},",
          "parent_menu_item = #{parentMenuItem,jdbcType=VARCHAR},",
          "menu_text = #{menuText,jdbcType=VARCHAR},",
          "target_url = #{targetUrl,jdbcType=VARCHAR},",
          "sort_order = #{sortOrder,jdbcType=SMALLINT},",
          "is_active = #{isActive,jdbcType=BIT},",
          "icon_class = #{iconClass,jdbcType=VARCHAR},",
          "sensitivity_level = #{sensitivityLevel,jdbcType=VARCHAR},",
          "creator = #{creator,jdbcType=VARCHAR},",
          "created = #{created,jdbcType=TIMESTAMP},",
          "modifier = #{modifier,jdbcType=VARCHAR},",
          "modified = #{modified,jdbcType=TIMESTAMP}",
        "where menu_item_id = #{menuItemId,jdbcType=VARCHAR}"
    })
    int updateByPrimaryKey(SystemDomainMenuItem row);
}